bag/urls.py
# pylint: disable=missing-module-docstring
# pylint: disable=unused-import
from django.contrib import admin  # noqa: F401
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>', views.remove_from_bag, name='remove_from_bag'),
]

boutique_ado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
# pylint: disable=missing-module-docstring,unused-import
from django.contrib import admin  # noqa: F401
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    # the int in front of the product id variable ensures that the product
    # details view won't accept 'add/' as part of a product ID. This occurs
    # Django always uses the first url it finds a matching pattern for.
    path('<int:product_id>/', views.product_details, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),  # noqa: E501
]

checkout/models.py
# pylint: disable=missing-module-docstring,missing-class-docstring,line-too-long,unused-import,no-member,unused-variable  # noqa: E501
import uuid  # noqa: F401

from django.db import models
from django.db.models import Sum  # noqa: F401
from django.conf import settings  # noqa: F401

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):  # noqa: DJ08

    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')  # noqa: E501
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)  # noqa: DJ01,E501
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)  # noqa: DJ01,E501
    county = models.CharField(max_length=80, null=True, blank=True)  # noqa: DJ01,E501
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)  # noqa: E501
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)  # noqa: E501
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)  # noqa: E501
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')  # noqa: E501

    def _generate_order_number(self):
        """
        Generate a random, unique number using UUID.
        """
        # function begins with an underscore to indicate that it is private
        # and only to be used by this class.
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        # Below we get the sum of a ll line item total fields for all
        # lineitem total fields for all lineitems on this order.
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0  # noqa: E501
        # Then, if the total is less than the delivery threshold, we multiply
        # it the percentage (in this case 10) to get the delivery charge.
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100  # noqa: E501
        else:
            # Otherwise it's 0
            self.delivery_cost = 0
        # Finally, we add this total to the delivery cost and we get the grand
        # total.
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        # The below 'super' code executes the original django save method
        # after a unique order number has been generated.
        super().save(*args, **kwargs)

        def __str__(self):
            return self.order_number


class OrderLineItem(models.Model):  # noqa: DJ08
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')  # noqa: E501
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)  # noqa: E501
    product_size = models.CharField(max_length=2, null=True, blank=True)  # XS, S, M, L, XL  # noqa: E501,DJ01
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)  # noqa: E501

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total and update
        the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        # The below 'super' code executes the original django save method
        # after a unique order number has been generated.
        super().save(*args, **kwargs)

        def __str__(self):
            return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
# pylint: disable=missing-module-docstring,missing-class-docstring,line-too-long  # noqa: E501
# pylint: disable=missing-function-docstring,invalid-str-returned
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    # null=True & blank=True settings make it so the friendly name is optional  # noqa: E501
    friendly_name = models.CharField(max_length=254, null=True, blank=True)  # noqa: DJ01,E501

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    # connects the two class via foreign key and assures product doesn't
    # get deleted on category change/deletion
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)  # noqa: E501
    sku = models.CharField(max_length=254, null=True, blank=True)  # noqa: DJ01
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)  # noqa: E501
    image_url = models.URLField(max_length=1024, null=True, blank=True)  # noqa: DJ01,E501
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
# pylint: disable=missing-module-docstring,no-member,missing-class-docstring
# pylint: disable=line-too-long
from django import forms
from .widgets import CustomClearableFileInpit
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInpit)  # noqa: E501

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        # pylint: disable=unused-variable
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
# pylint: disable=missing-module-docstring
from django.shortcuts import render, redirect, reverse, get_object_or_404  # noqa: E501
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category
from .forms import ProductForm

# Create your views here.


# pylint: disable=line-too-long
def all_products(request):
    """A view to (a kill) show all products in cluding sorting and search queiries """    # noqa: E501

    products = Product.objects.all()  # pylint: disable=maybe-no-member
    query = None  # ensure no error occurs when loading products page without a search term.  # noqa: E501
    categories = None
    sort = None  # pylint: disable=unused-variable
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey  # noqa: F841
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if sortkey == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'

            products = products.order_by(sortkey)

        if 'category' in request.GET:
            # categories in html page are split by commas to facilitate this
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)  # pylint: disable=maybe-no-member  # noqa: E501

        # below is labelled 'q' as that is it's labelled in the search form on the base template  # noqa: E501
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")  # noqa: E501
                return redirect(reverse('products'))

            # the 'i' before queries makes make it case INSENSITIVE!!!
            queries = Q(name__icontains=query) | Q(description__icontains=query)  # noqa: E501
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_details(request, product_id):
    """A view to (a kill) show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == "POST":
        # request.files ensures an image of the product will be captured if
        # one was submitted
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. \
                Please ensure the form is valid')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    # In case you've forgotten, pk is short for primary key
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')  # noqa: E501
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 cold-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'add_product' %}" method="post" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button></div>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`)
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 cold-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'edit_product' product.id %}" method="post" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Product</button></div>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`)
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                    {% else %}
                        <a href="#">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                    {% if product.category %}
                        <p class="small mt-1 mb-0">
                            <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                            </a>
                        </p>
                    {% endif %}
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a> |
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with product.has_sizes as s %}
                                {% if s %}
                                    <div class="col-12">
                                        <p><strong>Size:</strong></p>
                                        <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                            <option value="xs">XS</option>
                                            <option value="s">S</option>
                                            <option value="m" selected>M</option>
                                            <option value="l">L</option>
                                            <option value="xl">XL</option>
                                        </select>
                                    </div>
                                {% endif %}
                                <div class="col-12">
                                    <p class="mt-3"><strong>Quantity:</strong></p>
                                    <div class="form-group w-50">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <button class="decrement-qty btn btn-black rounded-0" 
                                                    data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-minus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                            <input class="form-control qty_input" type="number"
                                                name="quantity" value="1" min="1" max="99"
                                                data-item_id="{{ product.id }}"
                                                id="id_qty_{{ product.id }}">
                                            <div class="input-group-append">
                                                <button class="increment-qty btn btn-black rounded-0"
                                                    data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-plus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col{% if s %}-12 mt-2 {% endif %}">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <!-- The below input uses the request.path attribute to submit the current url to the view
                                        the form will be posted to. Thus enabling the user to be ridirected to the same page later.  -->
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}